/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddNoteResult = { 'ok' : ShiftView } |
  { 'notAuthorized' : null } |
  { 'notFound' : null };
export interface AllWorkersMonthlyReport {
  'month' : MonthKey,
  'shiftCount' : bigint,
  'workers' : Array<WorkerTotals>,
  'totalDurationNs' : bigint,
  'workerCount' : bigint,
}
export interface Cell { 'value' : Value, 'name' : string }
export type CorrectShiftResult = { 'ok' : ShiftView } |
  { 'notAuthorized' : null } |
  { 'invalidRange' : null } |
  { 'notFound' : null };
export type EndShiftResult = { 'ok' : ShiftView } |
  { 'noActiveShift' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExportResult = { 'ok' : string } |
  { 'notAuthorized' : null };
export type MonthKey = string;
export type NoteId = bigint;
export interface ReportShiftRow {
  'id' : ShiftId,
  'startTime' : Timestamp,
  'endTime' : [] | [Timestamp],
  'noteCount' : bigint,
  'durationNs' : bigint,
  'cappedAtLimit' : boolean,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Role = { 'owner' : null } |
  { 'worker' : null };
export type ShiftId = bigint;
export interface ShiftNote {
  'id' : NoteId,
  'createdAt' : Timestamp,
  'text' : string,
  'authorName' : string,
  'author' : WorkerId,
}
export interface ShiftQuery {
  'to' : [] | [Timestamp],
  'sortBy' : ShiftSort,
  'from' : [] | [Timestamp],
}
export type ShiftSort = { 'durationDesc' : null } |
  { 'dateAsc' : null } |
  { 'dateDesc' : null } |
  { 'durationAsc' : null };
export interface ShiftView {
  'id' : ShiftId,
  'startTime' : Timestamp,
  'endTime' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : Array<ShiftNote>,
  'worker' : WorkerId,
  'durationNs' : bigint,
  'cappedAtLimit' : boolean,
}
export type StartShiftResult = { 'ok' : ShiftView } |
  { 'alreadyActive' : ShiftView };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type WorkerId = Principal;
export interface WorkerMonthlyReport {
  'month' : MonthKey,
  'shifts' : Array<ReportShiftRow>,
  'shiftCount' : bigint,
  'averageDurationNs' : bigint,
  'totalDurationNs' : bigint,
  'worker' : WorkerId,
  'workerName' : string,
}
export interface WorkerSummary {
  'id' : WorkerId,
  'name' : string,
  'role' : Role,
  'email' : string,
  'totalDurationNs' : bigint,
  'totalShifts' : bigint,
  'lastShiftEnd' : [] | [Timestamp],
}
export interface WorkerTotals {
  'shiftCount' : bigint,
  'averageDurationNs' : bigint,
  'totalDurationNs' : bigint,
  'worker' : WorkerId,
  'workerName' : string,
}
export interface WorkerView {
  'id' : WorkerId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add a note to a shift. Allowed for the shift's worker and the owner.
   */
  'addShiftNote' : ActorMethod<[bigint, string], AddNoteResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Correct a shift's start/end times. Owner only.
   */
  'correctShift' : ActorMethod<
    [bigint, Timestamp, [] | [Timestamp]],
    CorrectShiftResult
  >,
  /**
   * / End the caller's active shift.
   */
  'endShift' : ActorMethod<[], EndShiftResult>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Export a monthly report as a downloadable CSV document. Owner only.
   */
  'exportMonthlyReport' : ActorMethod<[MonthKey], ExportResult>,
  /**
   * / Return the caller's currently running shift, if any.
   */
  'getActiveShift' : ActorMethod<[], [] | [ShiftView]>,
  /**
   * / Return the owner's monthly report across all workers. Owner only.
   */
  'getAllWorkersMonthlyReport' : ActorMethod<
    [MonthKey],
    AllWorkersMonthlyReport
  >,
  /**
   * / Return static Markdown documentation for this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Return the caller's own profile.
   */
  'getCallerProfile' : ActorMethod<[], [] | [WorkerView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Return the caller's own monthly report.
   */
  'getMyMonthlyReport' : ActorMethod<[MonthKey], WorkerMonthlyReport>,
  /**
   * / Return any worker's monthly report. Owner only.
   */
  'getWorkerMonthlyReport' : ActorMethod<
    [Principal, MonthKey],
    WorkerMonthlyReport
  >,
  /**
   * / Return any worker's profile. Owner only.
   */
  'getWorkerProfile' : ActorMethod<[Principal], [] | [WorkerView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's own shifts, filtered and sorted.
   */
  'listMyShifts' : ActorMethod<[ShiftQuery], Array<ShiftView>>,
  /**
   * / List any worker's shifts. Owner only.
   */
  'listWorkerShifts' : ActorMethod<[Principal, ShiftQuery], Array<ShiftView>>,
  /**
   * / List all workers with aggregate stats. Owner only.
   */
  'listWorkers' : ActorMethod<[], Array<WorkerSummary>>,
  /**
   * / Register the caller's profile on first sign-in, or return the existing one.
   */
  'registerProfile' : ActorMethod<[string, string], WorkerView>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Promote or demote a worker. Owner only.
   */
  'setWorkerRole' : ActorMethod<[Principal, Role], boolean>,
  /**
   * / Start a shift for the caller.
   */
  'startShift' : ActorMethod<[], StartShiftResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];