/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ShiftId = IDL.Nat;
export const Timestamp = IDL.Int;
export const NoteId = IDL.Nat;
export const WorkerId = IDL.Principal;
export const ShiftNote = IDL.Record({
  'id' : NoteId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : WorkerId,
});
export const ShiftView = IDL.Record({
  'id' : ShiftId,
  'startTime' : Timestamp,
  'endTime' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : IDL.Vec(ShiftNote),
  'worker' : WorkerId,
  'durationNs' : IDL.Int,
  'cappedAtLimit' : IDL.Bool,
});
export const AddNoteResult = IDL.Variant({
  'ok' : ShiftView,
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CorrectShiftResult = IDL.Variant({
  'ok' : ShiftView,
  'notAuthorized' : IDL.Null,
  'invalidRange' : IDL.Null,
  'notFound' : IDL.Null,
});
export const EndShiftResult = IDL.Variant({
  'ok' : ShiftView,
  'noActiveShift' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const MonthKey = IDL.Text;
export const ExportResult = IDL.Variant({
  'ok' : IDL.Text,
  'notAuthorized' : IDL.Null,
});
export const WorkerTotals = IDL.Record({
  'shiftCount' : IDL.Nat,
  'averageDurationNs' : IDL.Int,
  'totalDurationNs' : IDL.Int,
  'worker' : WorkerId,
  'workerName' : IDL.Text,
});
export const AllWorkersMonthlyReport = IDL.Record({
  'month' : MonthKey,
  'shiftCount' : IDL.Nat,
  'workers' : IDL.Vec(WorkerTotals),
  'totalDurationNs' : IDL.Int,
  'workerCount' : IDL.Nat,
});
export const Role = IDL.Variant({ 'owner' : IDL.Null, 'worker' : IDL.Null });
export const WorkerView = IDL.Record({
  'id' : WorkerId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : IDL.Text,
});
export const ReportShiftRow = IDL.Record({
  'id' : ShiftId,
  'startTime' : Timestamp,
  'endTime' : IDL.Opt(Timestamp),
  'noteCount' : IDL.Nat,
  'durationNs' : IDL.Int,
  'cappedAtLimit' : IDL.Bool,
});
export const WorkerMonthlyReport = IDL.Record({
  'month' : MonthKey,
  'shifts' : IDL.Vec(ReportShiftRow),
  'shiftCount' : IDL.Nat,
  'averageDurationNs' : IDL.Int,
  'totalDurationNs' : IDL.Int,
  'worker' : WorkerId,
  'workerName' : IDL.Text,
});
export const ShiftSort = IDL.Variant({
  'durationDesc' : IDL.Null,
  'dateAsc' : IDL.Null,
  'dateDesc' : IDL.Null,
  'durationAsc' : IDL.Null,
});
export const ShiftQuery = IDL.Record({
  'to' : IDL.Opt(Timestamp),
  'sortBy' : ShiftSort,
  'from' : IDL.Opt(Timestamp),
});
export const WorkerSummary = IDL.Record({
  'id' : WorkerId,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'totalDurationNs' : IDL.Int,
  'totalShifts' : IDL.Nat,
  'lastShiftEnd' : IDL.Opt(Timestamp),
});
export const StartShiftResult = IDL.Variant({
  'ok' : ShiftView,
  'alreadyActive' : ShiftView,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addShiftNote' : IDL.Func([IDL.Nat, IDL.Text], [AddNoteResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'correctShift' : IDL.Func(
      [IDL.Nat, Timestamp, IDL.Opt(Timestamp)],
      [CorrectShiftResult],
      [],
    ),
  'endShift' : IDL.Func([], [EndShiftResult], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'exportMonthlyReport' : IDL.Func([MonthKey], [ExportResult], ['query']),
  'getActiveShift' : IDL.Func([], [IDL.Opt(ShiftView)], ['query']),
  'getAllWorkersMonthlyReport' : IDL.Func(
      [MonthKey],
      [AllWorkersMonthlyReport],
      ['query'],
    ),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(WorkerView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyMonthlyReport' : IDL.Func([MonthKey], [WorkerMonthlyReport], ['query']),
  'getWorkerMonthlyReport' : IDL.Func(
      [IDL.Principal, MonthKey],
      [WorkerMonthlyReport],
      ['query'],
    ),
  'getWorkerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WorkerView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyShifts' : IDL.Func([ShiftQuery], [IDL.Vec(ShiftView)], ['query']),
  'listWorkerShifts' : IDL.Func(
      [IDL.Principal, ShiftQuery],
      [IDL.Vec(ShiftView)],
      ['query'],
    ),
  'listWorkers' : IDL.Func([], [IDL.Vec(WorkerSummary)], ['query']),
  'registerProfile' : IDL.Func([IDL.Text, IDL.Text], [WorkerView], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setWorkerRole' : IDL.Func([IDL.Principal, Role], [IDL.Bool], []),
  'startShift' : IDL.Func([], [StartShiftResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ShiftId = IDL.Nat;
  const Timestamp = IDL.Int;
  const NoteId = IDL.Nat;
  const WorkerId = IDL.Principal;
  const ShiftNote = IDL.Record({
    'id' : NoteId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : WorkerId,
  });
  const ShiftView = IDL.Record({
    'id' : ShiftId,
    'startTime' : Timestamp,
    'endTime' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'notes' : IDL.Vec(ShiftNote),
    'worker' : WorkerId,
    'durationNs' : IDL.Int,
    'cappedAtLimit' : IDL.Bool,
  });
  const AddNoteResult = IDL.Variant({
    'ok' : ShiftView,
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CorrectShiftResult = IDL.Variant({
    'ok' : ShiftView,
    'notAuthorized' : IDL.Null,
    'invalidRange' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const EndShiftResult = IDL.Variant({
    'ok' : ShiftView,
    'noActiveShift' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const MonthKey = IDL.Text;
  const ExportResult = IDL.Variant({
    'ok' : IDL.Text,
    'notAuthorized' : IDL.Null,
  });
  const WorkerTotals = IDL.Record({
    'shiftCount' : IDL.Nat,
    'averageDurationNs' : IDL.Int,
    'totalDurationNs' : IDL.Int,
    'worker' : WorkerId,
    'workerName' : IDL.Text,
  });
  const AllWorkersMonthlyReport = IDL.Record({
    'month' : MonthKey,
    'shiftCount' : IDL.Nat,
    'workers' : IDL.Vec(WorkerTotals),
    'totalDurationNs' : IDL.Int,
    'workerCount' : IDL.Nat,
  });
  const Role = IDL.Variant({ 'owner' : IDL.Null, 'worker' : IDL.Null });
  const WorkerView = IDL.Record({
    'id' : WorkerId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'email' : IDL.Text,
  });
  const ReportShiftRow = IDL.Record({
    'id' : ShiftId,
    'startTime' : Timestamp,
    'endTime' : IDL.Opt(Timestamp),
    'noteCount' : IDL.Nat,
    'durationNs' : IDL.Int,
    'cappedAtLimit' : IDL.Bool,
  });
  const WorkerMonthlyReport = IDL.Record({
    'month' : MonthKey,
    'shifts' : IDL.Vec(ReportShiftRow),
    'shiftCount' : IDL.Nat,
    'averageDurationNs' : IDL.Int,
    'totalDurationNs' : IDL.Int,
    'worker' : WorkerId,
    'workerName' : IDL.Text,
  });
  const ShiftSort = IDL.Variant({
    'durationDesc' : IDL.Null,
    'dateAsc' : IDL.Null,
    'dateDesc' : IDL.Null,
    'durationAsc' : IDL.Null,
  });
  const ShiftQuery = IDL.Record({
    'to' : IDL.Opt(Timestamp),
    'sortBy' : ShiftSort,
    'from' : IDL.Opt(Timestamp),
  });
  const WorkerSummary = IDL.Record({
    'id' : WorkerId,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'totalDurationNs' : IDL.Int,
    'totalShifts' : IDL.Nat,
    'lastShiftEnd' : IDL.Opt(Timestamp),
  });
  const StartShiftResult = IDL.Variant({
    'ok' : ShiftView,
    'alreadyActive' : ShiftView,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addShiftNote' : IDL.Func([IDL.Nat, IDL.Text], [AddNoteResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'correctShift' : IDL.Func(
        [IDL.Nat, Timestamp, IDL.Opt(Timestamp)],
        [CorrectShiftResult],
        [],
      ),
    'endShift' : IDL.Func([], [EndShiftResult], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'exportMonthlyReport' : IDL.Func([MonthKey], [ExportResult], ['query']),
    'getActiveShift' : IDL.Func([], [IDL.Opt(ShiftView)], ['query']),
    'getAllWorkersMonthlyReport' : IDL.Func(
        [MonthKey],
        [AllWorkersMonthlyReport],
        ['query'],
      ),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(WorkerView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyMonthlyReport' : IDL.Func(
        [MonthKey],
        [WorkerMonthlyReport],
        ['query'],
      ),
    'getWorkerMonthlyReport' : IDL.Func(
        [IDL.Principal, MonthKey],
        [WorkerMonthlyReport],
        ['query'],
      ),
    'getWorkerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WorkerView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyShifts' : IDL.Func([ShiftQuery], [IDL.Vec(ShiftView)], ['query']),
    'listWorkerShifts' : IDL.Func(
        [IDL.Principal, ShiftQuery],
        [IDL.Vec(ShiftView)],
        ['query'],
      ),
    'listWorkers' : IDL.Func([], [IDL.Vec(WorkerSummary)], ['query']),
    'registerProfile' : IDL.Func([IDL.Text, IDL.Text], [WorkerView], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setWorkerRole' : IDL.Func([IDL.Principal, Role], [IDL.Bool], []),
    'startShift' : IDL.Func([], [StartShiftResult], []),
  });
};

export const init = ({ IDL }) => { return []; };