/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type AddNoteResult = {
    __kind__: "ok";
    ok: ShiftView;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notFound";
    notFound: null;
};
export interface AllWorkersMonthlyReport {
    month: MonthKey;
    shiftCount: bigint;
    workers: Array<WorkerTotals>;
    totalDurationNs: bigint;
    workerCount: bigint;
}
export interface Cell {
    value: Value;
    name: string;
}
export type CorrectShiftResult = {
    __kind__: "ok";
    ok: ShiftView;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "invalidRange";
    invalidRange: null;
} | {
    __kind__: "notFound";
    notFound: null;
};
export type EndShiftResult = {
    __kind__: "ok";
    ok: ShiftView;
} | {
    __kind__: "noActiveShift";
    noActiveShift: null;
};
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type ExportResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
};
export type MonthKey = string;
export type NoteId = bigint;
export interface ReportShiftRow {
    id: ShiftId;
    startTime: Timestamp;
    endTime?: Timestamp;
    noteCount: bigint;
    durationNs: bigint;
    cappedAtLimit: boolean;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type ShiftId = bigint;
export interface ShiftNote {
    id: NoteId;
    createdAt: Timestamp;
    text: string;
    authorName: string;
    author: WorkerId;
}
export interface ShiftQuery {
    to?: Timestamp;
    sortBy: ShiftSort;
    from?: Timestamp;
}
export interface ShiftView {
    id: ShiftId;
    startTime: Timestamp;
    endTime?: Timestamp;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes: Array<ShiftNote>;
    worker: WorkerId;
    durationNs: bigint;
    cappedAtLimit: boolean;
}
export type StartShiftResult = {
    __kind__: "ok";
    ok: ShiftView;
} | {
    __kind__: "alreadyActive";
    alreadyActive: ShiftView;
};
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export type WorkerId = Principal;
export interface WorkerMonthlyReport {
    month: MonthKey;
    shifts: Array<ReportShiftRow>;
    shiftCount: bigint;
    averageDurationNs: bigint;
    totalDurationNs: bigint;
    worker: WorkerId;
    workerName: string;
}
export interface WorkerSummary {
    id: WorkerId;
    name: string;
    role: Role;
    email: string;
    totalDurationNs: bigint;
    totalShifts: bigint;
    lastShiftEnd?: Timestamp;
}
export interface WorkerTotals {
    shiftCount: bigint;
    averageDurationNs: bigint;
    totalDurationNs: bigint;
    worker: WorkerId;
    workerName: string;
}
export interface WorkerView {
    id: WorkerId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
}
export enum Role {
    owner = "owner",
    worker = "worker"
}
export enum ShiftSort {
    durationDesc = "durationDesc",
    dateAsc = "dateAsc",
    dateDesc = "dateDesc",
    durationAsc = "durationAsc"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Add a note to a shift. Allowed for the shift's worker and the owner.
     */
    addShiftNote(id: bigint, text: string): Promise<AddNoteResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Correct a shift's start/end times. Owner only.
     */
    correctShift(id: bigint, startTime: Timestamp, endTime: Timestamp | null): Promise<CorrectShiftResult>;
    /**
     * / End the caller's active shift.
     */
    endShift(): Promise<EndShiftResult>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Export a monthly report as a downloadable CSV document. Owner only.
     */
    exportMonthlyReport(month: MonthKey): Promise<ExportResult>;
    /**
     * / Return the caller's currently running shift, if any.
     */
    getActiveShift(): Promise<ShiftView | null>;
    /**
     * / Return the owner's monthly report across all workers. Owner only.
     */
    getAllWorkersMonthlyReport(month: MonthKey): Promise<AllWorkersMonthlyReport>;
    /**
     * / Return static Markdown documentation for this backend's public API.
     */
    getApiDoc(): Promise<string>;
    /**
     * / Return the caller's own profile.
     */
    getCallerProfile(): Promise<WorkerView | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Return the caller's own monthly report.
     */
    getMyMonthlyReport(month: MonthKey): Promise<WorkerMonthlyReport>;
    /**
     * / Return any worker's monthly report. Owner only.
     */
    getWorkerMonthlyReport(worker: Principal, month: MonthKey): Promise<WorkerMonthlyReport>;
    /**
     * / Return any worker's profile. Owner only.
     */
    getWorkerProfile(id: Principal): Promise<WorkerView | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List the caller's own shifts, filtered and sorted.
     */
    listMyShifts(filter: ShiftQuery): Promise<Array<ShiftView>>;
    /**
     * / List any worker's shifts. Owner only.
     */
    listWorkerShifts(worker: Principal, filter: ShiftQuery): Promise<Array<ShiftView>>;
    /**
     * / List all workers with aggregate stats. Owner only.
     */
    listWorkers(): Promise<Array<WorkerSummary>>;
    /**
     * / Register the caller's profile on first sign-in, or return the existing one.
     */
    registerProfile(email: string, name: string): Promise<WorkerView>;
    schema(): Promise<string>;
    /**
     * / Promote or demote a worker. Owner only.
     */
    setWorkerRole(id: Principal, role: Role): Promise<boolean>;
    /**
     * / Start a shift for the caller.
     */
    startShift(): Promise<StartShiftResult>;
}
import type { AddNoteResult as _AddNoteResult, Cell as _Cell, CorrectShiftResult as _CorrectShiftResult, EndShiftResult as _EndShiftResult, Error as _Error, ExportResult as _ExportResult, MonthKey as _MonthKey, ReportShiftRow as _ReportShiftRow, Result as _Result, Result__1 as _Result__1, Role as _Role, ShiftId as _ShiftId, ShiftNote as _ShiftNote, ShiftQuery as _ShiftQuery, ShiftSort as _ShiftSort, ShiftView as _ShiftView, StartShiftResult as _StartShiftResult, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, WorkerId as _WorkerId, WorkerMonthlyReport as _WorkerMonthlyReport, WorkerSummary as _WorkerSummary, WorkerView as _WorkerView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addShiftNote(arg0: bigint, arg1: string): Promise<AddNoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addShiftNote(arg0, arg1);
                return from_candid_AddNoteResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShiftNote(arg0, arg1);
            return from_candid_AddNoteResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async correctShift(arg0: bigint, arg1: Timestamp, arg2: Timestamp | null): Promise<CorrectShiftResult> {
        if (this.processError) {
            try {
                const result = await this.actor.correctShift(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
                return from_candid_CorrectShiftResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.correctShift(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
            return from_candid_CorrectShiftResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async endShift(): Promise<EndShiftResult> {
        if (this.processError) {
            try {
                const result = await this.actor.endShift();
                return from_candid_EndShiftResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endShift();
            return from_candid_EndShiftResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportMonthlyReport(arg0: MonthKey): Promise<ExportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.exportMonthlyReport(arg0);
                return from_candid_ExportResult_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportMonthlyReport(arg0);
            return from_candid_ExportResult_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveShift(): Promise<ShiftView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveShift();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveShift();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkersMonthlyReport(arg0: MonthKey): Promise<AllWorkersMonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkersMonthlyReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkersMonthlyReport(arg0);
            return result;
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerProfile(): Promise<WorkerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMonthlyReport(arg0: MonthKey): Promise<WorkerMonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMonthlyReport(arg0);
                return from_candid_WorkerMonthlyReport_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMonthlyReport(arg0);
            return from_candid_WorkerMonthlyReport_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerMonthlyReport(arg0: Principal, arg1: MonthKey): Promise<WorkerMonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerMonthlyReport(arg0, arg1);
                return from_candid_WorkerMonthlyReport_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerMonthlyReport(arg0, arg1);
            return from_candid_WorkerMonthlyReport_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerProfile(arg0: Principal): Promise<WorkerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMyShifts(arg0: ShiftQuery): Promise<Array<ShiftView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyShifts(to_candid_ShiftQuery_n37(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyShifts(to_candid_ShiftQuery_n37(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listWorkerShifts(arg0: Principal, arg1: ShiftQuery): Promise<Array<ShiftView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorkerShifts(arg0, to_candid_ShiftQuery_n37(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorkerShifts(arg0, to_candid_ShiftQuery_n37(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listWorkers(): Promise<Array<WorkerSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorkers();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorkers();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerProfile(arg0: string, arg1: string): Promise<WorkerView> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(arg0, arg1);
                return from_candid_WorkerView_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(arg0, arg1);
            return from_candid_WorkerView_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setWorkerRole(arg0: Principal, arg1: Role): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setWorkerRole(arg0, to_candid_Role_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWorkerRole(arg0, to_candid_Role_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async startShift(): Promise<StartShiftResult> {
        if (this.processError) {
            try {
                const result = await this.actor.startShift();
                return from_candid_StartShiftResult_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startShift();
            return from_candid_StartShiftResult_n45(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AddNoteResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddNoteResult): AddNoteResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CorrectShiftResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CorrectShiftResult): CorrectShiftResult {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_EndShiftResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EndShiftResult): EndShiftResult {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ExportResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportResult): ExportResult {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ReportShiftRow_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportShiftRow): ReportShiftRow {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return "owner" in value ? Role.owner : "worker" in value ? Role.worker : value;
}
function from_candid_ShiftView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShiftView): ShiftView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_StartShiftResult_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StartShiftResult): StartShiftResult {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerMonthlyReport_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerMonthlyReport): WorkerMonthlyReport {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerSummary_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerSummary): WorkerSummary {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerView_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerView): WorkerView {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShiftView]): ShiftView | null {
    return value.length === 0 ? null : from_candid_ShiftView_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkerView]): WorkerView | null {
    return value.length === 0 ? null : from_candid_WorkerView_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n18(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n22(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WorkerId;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    email: string;
}): {
    id: WorkerId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n30(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: _MonthKey;
    shifts: Array<_ReportShiftRow>;
    shiftCount: bigint;
    averageDurationNs: bigint;
    totalDurationNs: bigint;
    worker: _WorkerId;
    workerName: string;
}): {
    month: MonthKey;
    shifts: Array<ReportShiftRow>;
    shiftCount: bigint;
    averageDurationNs: bigint;
    totalDurationNs: bigint;
    worker: WorkerId;
    workerName: string;
} {
    return {
        month: value.month,
        shifts: from_candid_vec_n34(_uploadFile, _downloadFile, value.shifts),
        shiftCount: value.shiftCount,
        averageDurationNs: value.averageDurationNs,
        totalDurationNs: value.totalDurationNs,
        worker: value.worker,
        workerName: value.workerName
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ShiftId;
    startTime: _Timestamp;
    endTime: [] | [_Timestamp];
    noteCount: bigint;
    durationNs: bigint;
    cappedAtLimit: boolean;
}): {
    id: ShiftId;
    startTime: Timestamp;
    endTime?: Timestamp;
    noteCount: bigint;
    durationNs: bigint;
    cappedAtLimit: boolean;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.endTime)),
        noteCount: value.noteCount,
        durationNs: value.durationNs,
        cappedAtLimit: value.cappedAtLimit
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WorkerId;
    name: string;
    role: _Role;
    email: string;
    totalDurationNs: bigint;
    totalShifts: bigint;
    lastShiftEnd: [] | [_Timestamp];
}): {
    id: WorkerId;
    name: string;
    role: Role;
    email: string;
    totalDurationNs: bigint;
    totalShifts: bigint;
    lastShiftEnd?: Timestamp;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_Role_n30(_uploadFile, _downloadFile, value.role),
        email: value.email,
        totalDurationNs: value.totalDurationNs,
        totalShifts: value.totalShifts,
        lastShiftEnd: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.lastShiftEnd))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ShiftId;
    startTime: _Timestamp;
    endTime: [] | [_Timestamp];
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    notes: Array<_ShiftNote>;
    worker: _WorkerId;
    durationNs: bigint;
    cappedAtLimit: boolean;
}): {
    id: ShiftId;
    startTime: Timestamp;
    endTime?: Timestamp;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes: Array<ShiftNote>;
    worker: WorkerId;
    durationNs: bigint;
    cappedAtLimit: boolean;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.endTime)),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        notes: value.notes,
        worker: value.worker,
        durationNs: value.durationNs,
        cappedAtLimit: value.cappedAtLimit
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ShiftView;
} | {
    notAuthorized: null;
} | {
    invalidRange: null;
} | {
    notFound: null;
}): {
    __kind__: "ok";
    ok: ShiftView;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "invalidRange";
    invalidRange: null;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ShiftView_n7(_uploadFile, _downloadFile, value.ok)
    } : "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "invalidRange" in value ? {
        __kind__: "invalidRange",
        invalidRange: value.invalidRange
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ShiftView;
} | {
    noActiveShift: null;
}): {
    __kind__: "ok";
    ok: ShiftView;
} | {
    __kind__: "noActiveShift";
    noActiveShift: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ShiftView_n7(_uploadFile, _downloadFile, value.ok)
    } : "noActiveShift" in value ? {
        __kind__: "noActiveShift",
        noActiveShift: value.noActiveShift
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    notAuthorized: null;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ShiftView;
} | {
    alreadyActive: _ShiftView;
}): {
    __kind__: "ok";
    ok: ShiftView;
} | {
    __kind__: "alreadyActive";
    alreadyActive: ShiftView;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ShiftView_n7(_uploadFile, _downloadFile, value.ok)
    } : "alreadyActive" in value ? {
        __kind__: "alreadyActive",
        alreadyActive: from_candid_ShiftView_n7(_uploadFile, _downloadFile, value.alreadyActive)
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ShiftView;
} | {
    notAuthorized: null;
} | {
    notFound: null;
}): {
    __kind__: "ok";
    ok: ShiftView;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ShiftView_n7(_uploadFile, _downloadFile, value.ok)
    } : "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReportShiftRow>): Array<ReportShiftRow> {
    return value.map((x)=>from_candid_ReportShiftRow_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShiftView>): Array<ShiftView> {
    return value.map((x)=>from_candid_ShiftView_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerSummary>): Array<WorkerSummary> {
    return value.map((x)=>from_candid_WorkerSummary_n42(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return value == Role.owner ? {
        owner: null
    } : value == Role.worker ? {
        worker: null
    } : value;
}
function to_candid_ShiftQuery_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShiftQuery): _ShiftQuery {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_ShiftSort_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShiftSort): _ShiftSort {
    return value == ShiftSort.durationDesc ? {
        durationDesc: null
    } : value == ShiftSort.dateAsc ? {
        dateAsc: null
    } : value == ShiftSort.dateDesc ? {
        dateDesc: null
    } : value == ShiftSort.durationAsc ? {
        durationAsc: null
    } : value;
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to?: Timestamp;
    sortBy: ShiftSort;
    from?: Timestamp;
}): {
    to: [] | [_Timestamp];
    sortBy: _ShiftSort;
    from: [] | [_Timestamp];
} {
    return {
        to: value.to ? candid_some(value.to) : candid_none(),
        sortBy: to_candid_ShiftSort_n39(_uploadFile, _downloadFile, value.sortBy),
        from: value.from ? candid_some(value.from) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
